CREATE DATABASE IF NOT EXISTS indicador_hse;

USE indicador_hse;

CREATE TABLE IF NOT EXISTS funcionarios (
  id INT AUTO_INCREMENT PRIMARY KEY,
  data JSON
);

CREATE TABLE IF NOT EXISTS empresas (
  id INT AUTO_INCREMENT PRIMARY KEY,
  data JSON
);

CREATE TABLE IF NOT EXISTS ras_reunioes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  data JSON
);

CREATE TABLE IF NOT EXISTS usuarios (
  id INT AUTO_INCREMENT PRIMARY KEY,
  data JSON
);

CREATE TABLE IF NOT EXISTS historico_ras (
  id INT AUTO_INCREMENT PRIMARY KEY,
  data JSON
);

CREATE TABLE IF NOT EXISTS cpts (
  id INT AUTO_INCREMENT PRIMARY KEY,
  data JSON
);

CREATE TABLE IF NOT EXISTS inspecoes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  data JSON
);

CREATE TABLE IF NOT EXISTS categorias_hse (
  id INT AUTO_INCREMENT PRIMARY KEY,
  data JSON
);

CREATE TABLE IF NOT EXISTS areas_locais (
  id INT AUTO_INCREMENT PRIMARY KEY,
  data JSON
);

CREATE TABLE IF NOT EXISTS tipos_registro (
  id INT AUTO_INCREMENT PRIMARY KEY,
  data JSON
);

CREATE TABLE IF NOT EXISTS riscos_perigos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  data JSON
);

CREATE TABLE IF NOT EXISTS arts (
  id INT AUTO_INCREMENT PRIMARY KEY,
  data JSON
);