CREATE TABLE IF NOT EXISTS funcionarios (
  id SERIAL PRIMARY KEY,
  data JSONB NOT NULL
);

CREATE TABLE IF NOT EXISTS empresas (
  id SERIAL PRIMARY KEY,
  data JSONB NOT NULL
);

CREATE TABLE IF NOT EXISTS ras_reunioes (
  id SERIAL PRIMARY KEY,
  data JSONB NOT NULL
);

CREATE TABLE IF NOT EXISTS usuarios (
  id SERIAL PRIMARY KEY,
  data JSONB NOT NULL
);

CREATE TABLE IF NOT EXISTS historico_ras (
  id SERIAL PRIMARY KEY,
  data JSONB NOT NULL
);

CREATE TABLE IF NOT EXISTS cpts (
  id SERIAL PRIMARY KEY,
  data JSONB NOT NULL
);

CREATE TABLE IF NOT EXISTS inspecoes (
  id SERIAL PRIMARY KEY,
  data JSONB NOT NULL
);

CREATE TABLE IF NOT EXISTS categorias_hse (
  id SERIAL PRIMARY KEY,
  data JSONB NOT NULL
);

CREATE TABLE IF NOT EXISTS areas_locais (
  id SERIAL PRIMARY KEY,
  data JSONB NOT NULL
);

CREATE TABLE IF NOT EXISTS tipos_registro (
  id SERIAL PRIMARY KEY,
  data JSONB NOT NULL
);

CREATE TABLE IF NOT EXISTS riscos_perigos (
  id SERIAL PRIMARY KEY,
  data JSONB NOT NULL
);

CREATE TABLE IF NOT EXISTS arts (
  id SERIAL PRIMARY KEY,
  data JSONB NOT NULL
);

CREATE TABLE IF NOT EXISTS app_storage (
  storage_key TEXT PRIMARY KEY,
  data JSONB NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);